// <auto-generated />
namespace LoanerCalculator.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addaresultfield : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addaresultfield));
        
        string IMigrationMetadata.Id
        {
            get { return "201811252248315_Add a resultfield"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
